### ISSUE TITLE
 logowanie i rejestracja

### ISSUE THREAD

**Issue by tomaszkowalczyk94** [tomaszkowalczyk94/paradise-travels#4]
To jest w sumie trudny task, pociesze Cię ;D ALe da się zrobić. Musisz poczytać o sesjach w java EE.
User będzie zapisywany w bazie danych. W bazie będzie właśnie username i password. 

Możesz zrobić endpointy restowe, lub normalne formularze, jak chcesz w sumie ;p
tak na szybko znalazłem taki przykład, ale jest pewnie wiele w sieci: https://www.javatpoint.com/servlet-http-session-login-and-logout-example

**Comment by bogdan580** [comment]
**Zrobione**
